# Generated by Django 5.1.6 on 2025-03-02 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vector_search', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summary',
            old_name='user',
            new_name='user_id',
        ),
    ]
